{% set name = "numix-icon-theme" %}
{% set version = "25.12.09.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/numixproject/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 38f16c9fbb56d316b6bc75eb2a9bdb35e6b19770612250eed40e988fe20b5a6f

build:
  number: 0

requirements:
  build:
    # explicitly empty
  host:
    # explicitly empty

test:
  commands:
    - test -f ${PREFIX}/share/icons/Numix/24/mimetypes/jpg.svg  # [unix]
    - if not exist %PREFIX%\\Library\\share\\icons\\Numix\\24\\mimetypes\\jpg.svg exit 1  # [win]
    - test -f ${PREFIX}/share/icons/Numix-Light/24/status/state-ok.svg  # [unix]
    - if not exist %PREFIX%\\Library\\share\\icons\\Numix-Light\\24\\status\\state-ok.svg exit 1  # [win]

about:
  home: https://github.com/numixproject/numix-icon-theme
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: license
  summary: Official base icon theme from the Numix project.

extra:
  recipe-maintainers:
    - GiulioRomualdi
    - traversaro
